apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: oauth2-fullstack
spec:
  type: LoadBalancer
  selector:
    app: fastapi
    tier: backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001