version: '1.0'

services:
  db:
    image: postgres:15.1
    expose:
      - 5432
    env_file:
      - .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build: ./server
    ports:
      - 5001:5001
    env_file:
      - .env
    volumes:
      - ./server/:/usr/server/
    # command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 -m uvicorn app:app --reload --host 0.0.0.0 --port 5001'
    command: python3 -m uvicorn app:app --reload --host 0.0.0.0 --port 5001
    restart: always
    depends_on:
      - db

  nginx:
    build: ./
    ports:
      - 80:8080
    restart: always
    depends_on:
      - backend
    volumes:
      - ./conf.d:/etc/nginx/conf.d

volumes:
  postgres_data:

networks:
  default: 
    name: hello_fastapi