apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: oauth2-fullstack
spec:
  selector:
    app: postgresql
    tier: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
