apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: oauth2-fullstack
  labels:
    app: postgresql
    tier: backend
type: Opaque
data:
  POSTGRES_PASSWORD: ZmFzdGFwaV92dWVfcGFzc3dvcmQ=
  POSTGRES_USER: ZmFzdGFwaV92dWVfdXNlcg==
  POSTGRES_DB: ZmFzdGFwaV92dWVfcHJvZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: fastapi
  namespace: oauth2-fullstack
  labels:
    app: fastapi
    tier: backend
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vZmFzdGFwaV92dWVfdXNlcjpmYXN0YXBpX3Z1ZV9wYXNzd29yZEBkYjo1NDMyL2Zhc3RhcGlfdnVlX3Byb2Q=
  ACCESS_TOKEN_SECRET: WU9VUl9BQ0NFU1NfVE9LRU5fU0VDUkVU
  REFRESH_TOKEN_SECRET: WU9VUl9SRUZSRVNIX1RPS0VOX1NFQ1JFVA==